CREATE TABLE mahasiswa (
	id VARCHAR(40) NOT NULL,
	nim VARCHAR(40) NOT NULL,
	nama VARCHAR (200) NOT NULL,
	ipk FLOAT(4,2) NOT NULL,
	jurusan VARCHAR(25) NOT NULL,
    PRIMARY KEY(id)
	)ENGINE=InnoDB;
